NoUse
jdbc:mysql://localhost:3306/g_test1?characterEncoding=UTF-8
root
nuchiab4narukmakja
D:\\1_ActiveZone\\NetBean Projects\\2568\\templete_me\\web\\my_path\\
http://localhost:8084/templete_me/my_path/
D:\\1_ActiveZone\\NetBean Projects\\2568\\templete_me\\web\\file.bat
D:\\1_ActiveZone\\NetBean Projects\\2568\\templete_me\\web\\file.py